'use client';
import {useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {CalendarDays,Loader2,Mail,LockKeyhole} from 'lucide-react';
import {browserClient} from '@/lib/supabase/client';
import CalendarWorkspace from './workspace';
export default function Page(){
 const [session,setSession]=useState<Session|null>(null);const [loading,setLoading]=useState(true);const [configuration,setConfiguration]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;let unsubscribe=()=>{};try{const client=browserClient();client.auth.getSession().then(({data,error})=>{if(active){setSession(data.session);if(error)setError('Não foi possível recuperar a sessão. Entre novamente.');setLoading(false)}}).catch(()=>{if(active){setError('Não foi possível acessar sua conta. Tente novamente.');setLoading(false)}});const {data}=client.auth.onAuthStateChange((_event,s)=>{if(active)setSession(s)});unsubscribe=()=>data.subscription.unsubscribe()}catch{setConfiguration(true);setLoading(false)}return()=>{active=false;unsubscribe()}},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await browserClient().auth.signInWithPassword({email,password});if(error)setError('E-mail ou senha incorretos, ou conta indisponível.')}catch{setError('Não foi possível entrar. Confira sua conexão e tente novamente.')}finally{setBusy(false)}}
 if(loading)return <main className="auth-shell"><Loader2 className="spin" aria-label="Carregando"/></main>;
 if(session)return <CalendarWorkspace key={session.user.id}/>;
 return <main className="auth-shell"><div className="auth-card"><div className="auth-brand"><div className="brand-mark"><CalendarDays size={24}/></div><strong>cauan.</strong></div><p className="eyebrow">SEU ESPAÇO DE CONTEÚDO</p><h1>{configuration?'Conecte seu calendário':'Seu planejamento começa aqui.'}</h1><p className="auth-description">{configuration?'O painel está instalado. Configure as duas variáveis do Supabase na Vercel e siga o README do projeto para ativar o acesso.':'Entre para organizar as postagens de todas as suas empresas.'}</p>{!configuration&&<form onSubmit={login} className="editor-form"><label><span><Mail size={15}/>E-mail</span><input autoComplete="username" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com"/></label><label><span><LockKeyhole size={15}/>Senha</span><input autoComplete="current-password" type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Sua senha"/></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary-button full" disabled={busy}>{busy?<><Loader2 className="spin" size={16}/>Entrando…</>:'Entrar no calendário'}</button></form>}<p className="auth-footnote">{configuration?'Consulte as instruções de instalação no GitHub.':'Acesso privado · Cauan Videomaker'}</p></div></main>
}
