'use client';
import {useEffect,useState} from 'react';
import {browserClient} from '@/lib/supabase/client';
import {CalendarDays,Plus,ChevronLeft,ChevronRight,ImagePlus,Check,Clock,Settings2,Trash2,ImageIcon,LayoutGrid,Film,Loader2,Building2,PanelTop} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
type Company={id:string;name:string;color:string};
type Post={id:string;companyId:string;title:string;date:string;time:string;format:string;notes:string;image:string;published:number};
type Data={companies:Company[];posts:Post[]};
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateOf=(s:string)=>new Date(s+'T12:00:00');
const fmt=(s:string,options:Intl.DateTimeFormatOptions)=>dateOf(s).toLocaleDateString('pt-BR',options);
const colors=['#c78543','#527bd9','#b068ca','#2b8b6a','#db6275','#3b9eab'];
const formatIcon=(format:string)=>format==='Feed'?<LayoutGrid size={15}/>:format==='Reels'?<Film size={15}/>:<PanelTop size={15}/>;
async function api(body?:unknown){const r=await fetch('/api/data',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json() as {error?:string}&Data;if(r.status===401){await browserClient().auth.signOut();}if(!r.ok)throw new Error(d.error||'Não foi possível salvar.');return d as Data;}
export default function CalendarWorkspace(){return <SidebarProvider><Workspace/><Toaster position="top-center" richColors/></SidebarProvider>}
function Workspace(){
const [data,setData]=useState<Data>({companies:[],posts:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [companyId,setCompanyId]=useState('vianzo');const [month,setMonth]=useState('2026-10');const [selected,setSelected]=useState('2026-10-03');const [view,setView]=useState('month');const [filter,setFilter]=useState('all');const [editor,setEditor]=useState<Post|null>(null);const [companyEditor,setCompanyEditor]=useState<Company|null>(null);const [deletion,setDeletion]=useState<{kind:'post'|'company';id:string;name:string}|null>(null);const [busy,setBusy]=useState(false);const [pending,setPending]=useState<string[]>([]);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const {setOpenMobile}=useSidebar();
const load=async()=>{setLoading(true);try{setData(await api());setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
useEffect(()=>{void load()},[]);
useEffect(()=>{if(!file){setPreview('');return}const u=URL.createObjectURL(file);setPreview(u);return()=>URL.revokeObjectURL(u)},[file]);
const company=data.companies.find(c=>c.id===companyId);const allPosts=data.posts.filter(p=>p.companyId===companyId&&p.date.startsWith(month));const done=allPosts.filter(p=>p.published).length;const posts=data.posts.filter(p=>p.companyId===companyId&&(view==='week'||p.date.startsWith(month))).filter(p=>filter==='all'||(filter==='published'?p.published:!p.published));const dayPosts=posts.filter(p=>p.date===selected);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bahia',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const start=new Date(month+'-01T12:00:00');const weekday=(start.getDay()+6)%7;const last=new Date(start.getFullYear(),start.getMonth()+1,0).getDate();const days=Array.from({length:Math.ceil((weekday+last)/7)*7},(_,i)=>iso(new Date(start.getFullYear(),start.getMonth(),i-weekday+1)));
const weekDate=dateOf(selected);const monday=new Date(weekDate);monday.setDate(monday.getDate()-(monday.getDay()+6)%7);const weekDays=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return iso(d)});
const chooseCompany=(id:string)=>{setCompanyId(id);setOpenMobile(false)};
const changeMonth=(delta:number)=>{const d=new Date(start);d.setMonth(d.getMonth()+delta);const m=iso(d).slice(0,7);setMonth(m);setSelected(m+'-01')};
const moveWeek=(delta:number)=>{const d=dateOf(selected);d.setDate(d.getDate()+delta*7);setSelected(iso(d));setMonth(iso(d).slice(0,7))};
const openPost=(post?:Post,date=selected)=>{setFile(null);setEditor(post?{...post}:{id:crypto.randomUUID(),companyId,title:'',date,time:'09:30',format:'Stories',notes:'',image:'',published:0})};
const mutate=async(body:unknown,message:string)=>{const result=await api(body);setData(result);toast.success(message);return result};
const mark=async(p:Post)=>{setPending(x=>[...x,p.id]);try{await mutate({action:'setPublished',id:p.id,published:p.published?0:1},p.published?'Postagem voltou para pendente.':'Marcada como publicada.')}catch(e){toast.error((e as Error).message)}finally{setPending(x=>x.filter(id=>id!==p.id))}};
const savePost=async(e:React.FormEvent)=>{e.preventDefault();if(!editor||busy)return;setBusy(true);try{let image=editor.image;if(file){const f=new FormData();f.append('file',file);const r=await fetch('/api/images',{method:'POST',body:f});const d=await r.json() as {error?:string;url:string};if(!r.ok)throw new Error(d.error);image=d.url;setEditor({...editor,image});setFile(null)}await mutate({action:'savePost',post:{...editor,image}},'Postagem salva.');setCompanyId(editor.companyId);setMonth(editor.date.slice(0,7));setSelected(editor.date);setEditor(null)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
const saveCompany=async(e:React.FormEvent)=>{e.preventDefault();if(!companyEditor||busy)return;setBusy(true);try{await mutate({action:'saveCompany',company:companyEditor},'Empresa salva.');setCompanyId(companyEditor.id);setCompanyEditor(null)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
const remove=async()=>{if(!deletion||busy)return;setBusy(true);try{const d=await mutate({action:deletion.kind==='company'?'deleteCompany':'deletePost',id:deletion.id},deletion.kind==='company'?'Empresa removida.':'Postagem removida.');if(deletion.kind==='company'&&deletion.id===companyId)setCompanyId(d.companies[0]?.id??'');setDeletion(null);setEditor(null);if(deletion.kind==='company')setCompanyEditor(null)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'list_calendar_posts',title:'Consultar postagens',description:'Consultar postagens salvas no calendário de todas as empresas.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{const d=await api();setData(d);return d}}, {signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
return <>
<Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><div className="brand-mark"><CalendarDays size={23}/></div><div><strong>cauan<span>.</span></strong><small>ESTÚDIO DE CONTEÚDO</small></div></div></SidebarHeader><SidebarContent><div className="sidebar-section">PLANEJAMENTO</div><SidebarMenu><SidebarMenuItem><SidebarMenuButton className="nav-active" isActive><CalendarDays/><span>Calendário de postagens</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="sidebar-section section-row"><span>SUAS EMPRESAS</span><span>{data.companies.length}</span></div><SidebarMenu>{data.companies.map(c=><SidebarMenuItem key={c.id}><SidebarMenuButton size="lg" isActive={companyId===c.id} onClick={()=>chooseCompany(c.id)} className="company-button"><span className="company-avatar" style={{background:c.color+'20',color:c.color}}>{c.name.slice(0,1)}</span><span>{c.name}</span><span className="company-count">{data.posts.filter(p=>p.companyId===c.id&&p.date.startsWith(month)).length}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><button className="add-company" onClick={()=>setCompanyEditor({id:crypto.randomUUID(),name:'',color:colors[data.companies.length%colors.length]})}><Plus size={16}/>Adicionar empresa</button></SidebarContent><SidebarFooter><div className="sidebar-note"><Building2 size={19}/><p>Um calendário para<br/>cada empresa.</p></div><div className="profile"><div>CV</div><span><strong>Cauan Videomaker</strong><small>Meu espaço de trabalho</small></span><button className="signout" onClick={async()=>{const {error}=await browserClient().auth.signOut();if(error)toast.error("Não foi possível sair. Tente novamente.")}}>Sair</button></div></SidebarFooter></Sidebar>
<main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-trigger" aria-label="Abrir empresas"/><span>Meu espaço</span><span className="slash">/</span><strong>Calendário</strong></div><div className="top-label"><span className="private-dot"/>Espaço privado</div></header>
<div className="main-content"><div className="heading"><div><p className="eyebrow">PLANEJAR. CRIAR. PUBLICAR.</p><h1>Calendário de postagens</h1><p className="subheading">Todas as publicações, no seu ritmo.</p></div><button className="primary-button" onClick={()=>openPost()} disabled={!company}><Plus size={18}/>Nova postagem</button></div>
{error?<div className="error-state"><p>{error}</p><button className="secondary-button" onClick={load}>Tentar novamente</button></div>:loading?<div className="loading-state"><Skeleton className="h-24 w-full"/><Skeleton className="h-96 w-full"/></div>:!company?<div className="empty-company"><Building2 size={40}/><h2>Comece com uma empresa</h2><p>Adicione uma empresa para organizar suas postagens.</p><button className="primary-button" onClick={()=>setCompanyEditor({id:crypto.randomUUID(),name:'',color:colors[0]})}><Plus size={18}/>Adicionar empresa</button></div>:<>
<div className="company-heading"><span className="company-avatar" style={{background:company.color+'20',color:company.color}}>{company.name.slice(0,1)}</span><h2>{company.name}</h2><button className="icon-button" aria-label="Editar empresa" title="Editar empresa" onClick={()=>setCompanyEditor({...company})}><Settings2 size={17}/></button><span className="company-tag">Calendário da empresa</span></div>
<div className="stats"><div className="stat"><span>Planejadas no mês</span><strong>{allPosts.length}<CalendarDays/></strong><small>{allPosts.filter(p=>p.format==='Feed').length} Feed · {allPosts.filter(p=>p.format==='Stories').length} Stories · {allPosts.filter(p=>p.format==='Reels').length} Reels</small></div><div className="stat"><span>Publicadas</span><strong>{done}<Check/></strong><Progress value={allPosts.length?done/allPosts.length*100:0} className="month-progress"/><small>{allPosts.length?Math.round(done/allPosts.length*100):0}% do planejamento concluído</small></div><div className="stat"><span>Aguardando publicação</span><strong>{allPosts.length-done}<Clock/></strong><small>Marque cada postagem quando publicar</small></div></div>
<section className="calendar-panel" aria-label="Calendário de postagens"><div className="calendar-toolbar"><div className="month-control"><button className="icon-button" aria-label={view==='week'?'Semana anterior':'Mês anterior'} onClick={()=>view==='week'?moveWeek(-1):changeMonth(-1)}><ChevronLeft size={19}/></button><h2>{start.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h2><button className="icon-button" aria-label={view==='week'?'Próxima semana':'Próximo mês'} onClick={()=>view==='week'?moveWeek(1):changeMonth(1)}><ChevronRight size={19}/></button><button className="today-button" onClick={()=>{setMonth(today.slice(0,7));setSelected(today)}}>Hoje</button></div><div className="calendar-options"><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filtrar status" className="status-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas as postagens</SelectItem><SelectItem value="pending">Pendentes</SelectItem><SelectItem value="published">Publicadas</SelectItem></SelectContent></Select><Tabs value={view} onValueChange={setView}><TabsList className="view-tabs"><TabsTrigger value="month">Mês</TabsTrigger><TabsTrigger value="week">Semana</TabsTrigger></TabsList></Tabs></div></div>
<div className="weekdays">{['SEG','TER','QUA','QUI','SEX','SÁB','DOM'].map(d=><span key={d}>{d}</span>)}</div>
<div className={view==='week'?'calendar-grid week-grid':'calendar-grid'}>{(view==='week'?weekDays:days).map(d=>{const items=posts.filter(p=>p.date===d);const isCurrent=d.startsWith(month);return <button key={d} aria-label={`${fmt(d,{day:'numeric',month:'long'})}, ${items.length} postagens`} aria-pressed={d===selected} className={`day ${!isCurrent?'outside':''} ${selected===d?'selected':''} ${d===today?'is-today':''}`} onClick={()=>{setSelected(d);if(!isCurrent)setMonth(d.slice(0,7))}}><span className="day-number">{dateOf(d).getDate()}</span>{items.length>0?<><div className="day-items">{(view==='week'?items:items.slice(0,2)).map(p=><div className={`calendar-item ${p.format.toLowerCase()} ${p.published?'is-published':''}`} key={p.id}>{p.image?<img src={p.image} alt=""/>:formatIcon(p.format)}<span>{p.time} <b>{p.format}</b></span>{p.published&&<Check size={12}/>}</div>)}</div><span className="mobile-post-count">{items.length} posts</span>{view==='month'&&items.length>2&&<span className="more-posts">+{items.length-2} {items.length-2===1?'postagem':'postagens'}</span>}</>:view==='week'?<span className="day-empty">Sem postagens</span>:null}</button>})}</div>
<div className="calendar-footer"><div className="legend"><span><i className="feed-dot"/>Feed</span><span><i className="stories-dot"/>Stories</span><span><i className="reels-dot"/>Reels</span></div><span>Horários de Brasília</span></div></section>
<section className="daily-section"><div className="daily-heading"><div><p className="eyebrow">POSTAGENS DO DIA</p><h2>{fmt(selected,{weekday:'long',day:'numeric',month:'long'})}<span>{dayPosts.length}</span></h2></div><button className="secondary-button" onClick={()=>openPost(undefined,selected)}><Plus size={16}/>Adicionar neste dia</button></div>{dayPosts.length===0?<div className="empty-day"><CalendarDays size={28}/><div><strong>{filter==='all'?'Dia livre no calendário':'Nenhuma postagem neste filtro'}</strong><p>{filter==='all'?'Adicione uma postagem para começar.':'Experimente selecionar todas as postagens.'}</p></div></div>:<div className="post-grid">{dayPosts.map(p=><article className={`post-card ${p.published?'published-card':''}`} key={p.id}><button className="post-image" onClick={()=>openPost(p)} aria-label={`Editar imagem de ${p.title}`}>{p.image?<img src={p.image} alt={p.title}/>:<div className="image-placeholder"><ImagePlus size={30}/><span>Adicionar imagem</span></div>}<span className={`format-badge ${p.format.toLowerCase()}`}>{formatIcon(p.format)}{p.format}</span></button><div className="post-details"><div className="post-time"><Clock size={14}/>{p.time}<span className={p.published?'published-status':'pending-status'}>{p.published?'Publicado':'Pendente'}</span></div><button className="post-title" onClick={()=>openPost(p)}>{p.title}</button><p className="post-notes">{p.notes||'Sem observações'}</p><div className="post-actions"><label><Checkbox checked={!!p.published} disabled={pending.includes(p.id)} onCheckedChange={()=>void mark(p)} aria-label={`Marcar ${p.title} como ${p.published?'pendente':'publicado'}`}/><span>Já publiquei</span></label><button onClick={()=>openPost(p)}>Editar</button></div></div></article>)}</div>}</section>
</>}
<footer className="page-footer">cauan<span>.</span><p>Seu conteúdo, bem organizado.</p></footer></div></main>
<Sheet open={!!editor} onOpenChange={open=>{if(!open&&!busy)setEditor(null)}}><SheetContent className="editor-sheet"><SheetHeader><SheetTitle>{data.posts.some(p=>p.id===editor?.id)?'Editar postagem':'Nova postagem'}</SheetTitle><SheetDescription>Organize o conteúdo e marque quando publicar.</SheetDescription></SheetHeader>{editor&&<form onSubmit={savePost} className="editor-form"><label className="upload-zone">{preview||editor.image?<img src={preview||editor.image} alt="Prévia da postagem"/>:<><ImagePlus size={32}/><strong>Adicionar imagem</strong></>}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>3*1024*1024){toast.error('A imagem deve ter até 3 MB.');return}setFile(f)}}}/><span>{preview||editor.image?'Trocar imagem':'JPG, PNG, WebP ou GIF · até 3 MB'}</span></label>{(editor.image||file)&&<button type="button" className="remove-image" disabled={busy} onClick={()=>{setFile(null);setEditor({...editor,image:''})}}>Remover imagem</button>}<label>Título<input required maxLength={150} value={editor.title} placeholder="Ex.: Café da tarde + toast" onChange={e=>setEditor({...editor,title:e.target.value})}/></label><label>Empresa<Select value={editor.companyId} onValueChange={v=>setEditor({...editor,companyId:v})}><SelectTrigger className="form-select"><SelectValue/></SelectTrigger><SelectContent>{data.companies.map(c=><SelectItem value={c.id} key={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label><div className="form-row"><label>Data<input type="date" required value={editor.date} onChange={e=>setEditor({...editor,date:e.target.value})}/></label><label>Horário<input type="time" required value={editor.time} onChange={e=>setEditor({...editor,time:e.target.value})}/></label></div><label>Formato<Select value={editor.format} onValueChange={v=>setEditor({...editor,format:v})}><SelectTrigger className="form-select"><SelectValue/></SelectTrigger><SelectContent>{['Feed','Stories','Reels'].map(f=><SelectItem key={f} value={f}>{f}</SelectItem>)}</SelectContent></Select></label><label>Legenda ou observações<textarea maxLength={5000} rows={4} value={editor.notes} placeholder="Escreva a legenda ou lembretes para publicar…" onChange={e=>setEditor({...editor,notes:e.target.value})}/></label><label className="check-label"><Checkbox checked={!!editor.published} onCheckedChange={v=>setEditor({...editor,published:v?1:0})}/>Já publiquei esta postagem</label><button type="submit" disabled={busy} className="primary-button full">{busy?<Loader2 className="spin" size={17}/>:<Check size={17}/>} {busy?'Salvando…':'Salvar postagem'}</button>{data.posts.some(p=>p.id===editor.id)&&<button type="button" disabled={busy} className="danger-button" onClick={()=>setDeletion({kind:'post',id:editor.id,name:editor.title})}><Trash2 size={16}/>Excluir postagem</button>}</form>}</SheetContent></Sheet>
<Dialog open={!!companyEditor} onOpenChange={open=>{if(!open&&!busy)setCompanyEditor(null)}}><DialogContent className="company-dialog"><DialogHeader><DialogTitle>{data.companies.some(c=>c.id===companyEditor?.id)?'Editar empresa':'Adicionar empresa'}</DialogTitle><DialogDescription>Cada empresa tem seu próprio calendário.</DialogDescription></DialogHeader>{companyEditor&&<form onSubmit={saveCompany} className="editor-form"><label>Nome da empresa<input required maxLength={80} autoFocus value={companyEditor.name} placeholder="Nome da empresa" onChange={e=>setCompanyEditor({...companyEditor,name:e.target.value})}/></label><fieldset><legend>Cor de identificação</legend><div className="color-picker">{colors.map(c=><button key={c} type="button" style={{background:c}} aria-label={`Cor ${c}`} aria-pressed={companyEditor.color===c} onClick={()=>setCompanyEditor({...companyEditor,color:c})}>{companyEditor.color===c&&<Check size={18}/>}</button>)}</div></fieldset><button className="primary-button full" disabled={busy}>{busy?'Salvando…':'Salvar empresa'}</button>{data.companies.some(c=>c.id===companyEditor.id)&&<button type="button" className="danger-button" disabled={busy} onClick={()=>setDeletion({kind:'company',id:companyEditor.id,name:companyEditor.name})}><Trash2 size={16}/>Remover empresa</button>}</form>}</DialogContent></Dialog>
<AlertDialog open={!!deletion} onOpenChange={open=>{if(!open&&!busy)setDeletion(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir {deletion?.name}?</AlertDialogTitle><AlertDialogDescription>{deletion?.kind==='company'?'A empresa e todas as suas postagens serão removidas. Essa ação não pode ser desfeita.':'Esta postagem será removida do calendário. Essa ação não pode ser desfeita.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><button className="danger-confirm" disabled={busy} onClick={remove}>{busy?'Excluindo…':'Confirmar exclusão'}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
</>}
